### PR TITLE
Add "nolinks" command for copy and past

### PR DESCRIPTION
**Pull request by sklaes**

### CODE REVIEW

**Review by osm0sis — COMMENTED** [review]
`su; echo "nolinks" > /data/.busybox-ndk` wouldn't work, since the echo command wouldn't be in the su subshell.

**Comment by sklaes** [comment]
@osm0sis
yes you are right - that dosn't work that way.
I just didn't want to break the existing layout

**Comment by osm0sis** [comment]
I don't see how it would break anything, are you going to fix it?

**Comment by osm0sis** [comment]
I don't see how it would break anything.

Also, the readme directs people to go read the release post for special features, and that includes nolinks.

**Pull request closed without merging**
